### ISSUE TITLE
About package 'framework.Semantic'

### ISSUE THREAD

**Issue by lzyplayer** [elect86/helloTriangle#3]
I have just finished importing the jogl jars on IntelIJ, now I'm trying to run the triangle hello world(https://github.com/jvm-graphics-labs/hello-triangle/blob/master/src/main/java/gl4/HelloTriangleSimple.java). however, my IDE cannot resolve line `import framework.Semantic;`(which means I haven't got this packet), neither can IntelIJ  find the jar on net automatically. 

appreciate for any reply!

```java

import com.jogamp.newt.event.*;
import com.jogamp.newt.opengl.GLWindow;
import com.jogamp.opengl.*;
import com.jogamp.opengl.math.FloatUtil;
import com.jogamp.opengl.util.Animator;
import com.jogamp.opengl.util.GLBuffers;
import com.jogamp.opengl.util.glsl.ShaderCode;
import com.jogamp.opengl.util.glsl.ShaderProgram;

import framework.Semantic; //every single line work out fine except this one

import java.nio.ByteBuffer;
import java.nio.FloatBuffer;
import java.nio.IntBuffer;
import java.nio.ShortBuffer;

import static com.jogamp.opengl.GL.*;
import static com.jogamp.opengl.GL.GL_FLOAT;
import static com.jogamp.opengl.GL.GL_TRIANGLES;
import static com.jogamp.opengl.GL.GL_UNSIGNED_SHORT;
import static com.jogamp.opengl.GL2ES2.GL_DEBUG_SEVERITY_HIGH;
import static com.jogamp.opengl.GL2ES2.GL_DEBUG_SEVERITY_MEDIUM;
import static com.jogamp.opengl.GL2ES3.*;
import static com.jogamp.opengl.GL2ES3.GL_UNIFORM_BUFFER;
import static com.jogamp.opengl.GL4.GL_MAP_COHERENT_BIT;
import static com.jogamp.opengl.GL4.GL_MAP_PERSISTENT_BIT;
```

the .jar I included in intelij module:

1. gluegen-rt.jar 
2. jogl-all.jar 
3. gluegen-java-src.zip 
4. jogl-java-src.zip 
5. gluegen-rt-natives-windows-amd64.jar 
6. jogl-all-natives-windows-amd64.jar

**Comment by elect86** [comment]
Hi,

sorry for the delay, anyway, the file is [this one](https://github.com/jvm-graphics-labs/hello-triangle/blob/master/src/main/java/framework/Semantic.java)

You should rely on the gradle wrapper for the dependencies
